// mobile/src/chat/OptionButtons.tsx
import { useEffect, useRef, useState } from 'react';
import { Linking, Pressable, Text, View } from 'react-native';
import { StyleSheet, useUnistyles } from 'react-native-unistyles';
import { kindOf, isPermission, questionParts } from '@hangar/core';
import * as m from '../paraglide/messages';
import { superficie } from '../theme/superficie';
import { Icon } from '../ui/Icon';
import { semEmoji } from '../ui/semEmoji';
import { useAparencia } from '../stores/aparencia';

interface Props {
  question: string;
  options: string[];
  onSelect: (n: number) => void | Promise<void>;
  onCancel: () => void | Promise<void>;
  /** Envia as opções marcadas (só múltipla escolha). Ausente = sem botão de enviar. */
  onSubmit?: () => void | Promise<void>;
}

// MÚLTIPLA ESCOLHA: o TUI desenha a caixinha antes do rótulo ("[ ] Alfa", "[✔] Alfa"), e só por ela
// dá pra saber. Marcar e enviar são ações diferentes: o toque alterna, quem envia é o botão.
const CAIXA = /^\[(.?)\]\s*/;
const marcada = (o: string) => /^\[[^\s\]]\]/.test(o);

export function OptionButtons({ question, options, onSelect, onCancel, onSubmit }: Props) {
  const { theme } = useUnistyles();
  const permission = isPermission(options);
  const kinds = options.map((o) => kindOf(o));
  const multipla = options.some((o) => CAIXA.test(o));
  const marcadas = options.filter(marcada).length;
  const locked = useRef(false);
  const mounted = useRef(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  // Aparência › Destaque das perguntas: a moldura do pedido que espera a pessoa.
  const destaque = useAparencia((s) => s.destaquePergunta);
  useEffect(() => {
    mounted.current = true;
    return () => { mounted.current = false; };
  }, []);
  async function run(action: () => void | Promise<void>) {
    if (locked.current) return;
    locked.current = true;
    setBusy(true);
    setError('');
    try { await action(); }
    catch (e) {
      if (mounted.current) setError(e instanceof Error ? e.message : m.comum_falha_envio_opcao());
    } finally {
      locked.current = false;
      if (mounted.current) setBusy(false);
    }
  }

  return (
    <View style={[styles.wrap, { borderColor: destaque === 'amber' ? theme.tokens.status.warning : theme.tokens.accent.base }]}>
      {permission ? (
        <View style={[styles.permChip, { backgroundColor: theme.tokens.accent.dim }]}>
          <Icon name="ShieldAlert" size={13} color={theme.tokens.accent.base} />
          <Text style={[styles.permTxt, { color: theme.tokens.accent.base }]}>{semEmoji(m.permissao_pedido())}</Text>
        </View>
      ) : null}
      <Text style={[styles.question, { color: theme.tokens.text.primary }]}>
        {questionParts(question).map((part, i) =>
          part.kind === 'code' ? (
            <Text key={i} style={[styles.qCode, { backgroundColor: superficie(theme, 0.8), color: theme.tokens.text.primary }]}>
              {part.text}
            </Text>
          ) : part.kind === 'link' ? (
            <Text
              key={i}
              accessibilityRole="link"
              style={{ color: theme.tokens.accent.base, textDecorationLine: 'underline' }}
              onPress={() => void Linking.openURL(part.text).catch((e: unknown) => setError(e instanceof Error ? e.message : m.comum_falha_envio_opcao()))}
            >
              {part.text}
            </Text>
          ) : (
            part.text
          ),
        )}
      </Text>
      <View style={styles.list}>
        {options.map((opt, i) => {
          const kind = kinds[i];
          const isAllow = permission && kind === 'allow';
          const isAlways = permission && kind === 'always';
          const isDeny = permission && kind === 'deny';
          return (
            <Pressable
              key={i}
              onPress={() => void run(() => onSelect(i + 1))}
              disabled={busy}
              accessibilityState={{ disabled: busy, busy, checked: multipla ? marcada(opt) : undefined }}
              style={[
                styles.btn,
                { backgroundColor: superficie(theme, 0.8), borderColor: theme.tokens.border.default },
                isAllow && { backgroundColor: theme.tokens.accent.base, borderColor: theme.tokens.accent.base },
                isAlways && { backgroundColor: theme.tokens.accent.dim, borderColor: theme.tokens.accent.base },
                isDeny && { borderColor: theme.tokens.status.error },
              ]}
              accessibilityRole="button"
            >
              <Text
                style={[
                  styles.num,
                  { color: theme.tokens.text.secondary },
                  isAllow && { color: '#fff' },
                  isAlways && { color: theme.tokens.accent.base },
                  isDeny && { color: theme.tokens.status.error },
                ]}
              >
                {i + 1}.
              </Text>
              {multipla ? (
                <View
                  style={[styles.caixa, { borderColor: theme.tokens.border.default }, marcada(opt) && { backgroundColor: theme.tokens.accent.base, borderColor: theme.tokens.accent.base }]}
                  accessibilityElementsHidden
                  importantForAccessibility="no-hide-descendants"
                >
                  {marcada(opt) ? <Icon name="Check" size={12} color="#fff" /> : null}
                </View>
              ) : null}
              <Text
                style={[
                  styles.optTxt,
                  { color: theme.tokens.text.primary },
                  isAllow && { color: '#fff' },
                  isAlways && { color: theme.tokens.accent.base },
                  isDeny && { color: theme.tokens.status.error },
                ]}
              >
                {multipla ? opt.replace(CAIXA, '') : opt}
              </Text>
            </Pressable>
          );
        })}
        {multipla && onSubmit ? (
          <Pressable
            onPress={() => void run(onSubmit)}
            disabled={busy || marcadas === 0}
            accessibilityState={{ disabled: busy || marcadas === 0, busy }}
            style={[styles.btn, { backgroundColor: theme.tokens.accent.base, borderColor: theme.tokens.accent.base }, marcadas === 0 && styles.off]}
            accessibilityRole="button"
          >
            <Icon name="Send" size={14} color="#fff" />
            <Text style={[styles.optTxt, { color: '#fff' }]}>{m.opcoes_enviar_marcadas({ n: marcadas })}</Text>
          </Pressable>
        ) : null}
        <Pressable
          onPress={() => void run(onCancel)}
          disabled={busy}
          accessibilityState={{ disabled: busy, busy }}
          style={[styles.btn, styles.btnCancel, { borderColor: theme.tokens.status.error }]}
          accessibilityRole="button"
        >
          <Text style={[styles.num, { color: theme.tokens.status.error }]}>✕</Text>
          <Text style={[styles.optTxt, { color: theme.tokens.status.error }]}>{m.comum_cancelar()}</Text>
        </Pressable>
      </View>
      {error ? <Text accessibilityRole="alert" style={{ color: theme.tokens.status.error }}>{error}</Text> : null}
    </View>
  );
}

const styles = StyleSheet.create((theme) => ({
  wrap: {
    padding: theme.base.space[3],
    gap: theme.base.space[3],
    borderWidth: 1,
    borderRadius: 14,
  },
  permChip: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: theme.base.radius.full,
    paddingHorizontal: theme.base.space[2],
    paddingVertical: 4,
  },
  permTxt: {
    fontSize: theme.base.text.xs,
    fontWeight: '600',
  },
  question: {
    fontSize: theme.base.text.base,
    fontWeight: '500',
    lineHeight: 22,
  },
  qCode: {
    fontFamily: theme.base.fontMono,
    fontSize: 14,
    paddingHorizontal: 4,
    borderRadius: 4,
  },
  list: {
    gap: theme.base.space[2],
  },
  btn: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.base.space[3],
    paddingHorizontal: theme.base.space[3],
    borderWidth: 1,
    borderRadius: theme.base.radius.lg,
  },
  btnCancel: {
    borderColor: theme.tokens.status.error,
  },
  num: {
    fontFamily: theme.base.fontMono,
    fontSize: theme.base.text.sm,
    minWidth: 20,
  },
  optTxt: {
    fontSize: theme.base.text.base,
    flex: 1,
  },
  caixa: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  off: {
    opacity: 0.45,
  },
}));

// frontend/src/components/OptionButtons.svelte
<script lang="ts">
  import * as m from '../paraglide/messages';
  import { kindOf, isPermission as isPermissionFn, questionParts } from '@hangar/core';
  interface Props {
    question: string;
    options: string[];
    onSelect: (index: number) => void;
    onCancel: () => void;
    /** Envia as opções já marcadas (só múltipla escolha). Ausente = sem botão de enviar. */
    onSubmit?: () => void;
  }
  let { question, options, onSelect, onCancel, onSubmit }: Props = $props();

  // MÚLTIPLA ESCOLHA: o TUI desenha a caixinha antes do rótulo ("[ ] Alfa", "[✔] Alfa"), e é só
  // por ela que dá pra saber — o pane não diz de outro jeito. Aqui marcar e enviar são ações
  // DIFERENTES: cada toque alterna uma opção e o picker continua aberto; quem envia é o botão.
  // Sem isso dava pra marcar e não dava pra enviar, e a única saída era Cancelar (relatado com
  // print, 28/08/2026).
  const CAIXA = /^\[(.?)\]\s*/;
  const multipla = $derived(options.some((o) => CAIXA.test(o)));
  const marcadas = $derived(options.filter((o) => /^\[[^\s\]]\]/.test(o)).length);
  /** Rótulo sem a caixinha — ela vira o estado visual do botão, não texto. */
  function semCaixa(o: string): string { return o.replace(CAIXA, ''); }
  function marcada(o: string): boolean { return /^\[[^\s\]]\]/.test(o); }

  const kinds = $derived(options.map(kindOf));
  const isPermission = $derived(isPermissionFn(options));
</script>

<div class="options-wrap">
  {#if isPermission}
    <span class="perm-chip">{m.permissao_pedido()}</span>
  {/if}
  <p class="question">
    <!-- Crases viram <code>; URL http(s) vira link que abre fora do app. -->
    {#each questionParts(question) as part}{#if part.kind === 'code'}<code class="q-code">{part.text}</code>{:else if part.kind === 'link'}<a class="q-link" href={part.text} target="_blank" rel="noopener noreferrer">{part.text}</a>{:else}{part.text}{/if}{/each}
  </p>
  <div class="options-list">
    {#each options as opt, i}
      <button
        class="option-btn"
        class:option-btn--allow={isPermission && kinds[i] === 'allow'}
        class:option-btn--always={isPermission && kinds[i] === 'always'}
        class:option-btn--deny={isPermission && kinds[i] === 'deny'}
        style="animation-delay: {i * 40}ms"
        onclick={() => onSelect(i + 1)}
        aria-pressed={multipla ? marcada(opt) : undefined}
      >
        <span class="opt-num">{i + 1}.</span>
        {#if multipla}
          <!-- Decorativo: quem anuncia marcado/desmarcado e o aria-pressed do botao. -->
          <span class="opt-caixa" class:opt-caixa--on={marcada(opt)} aria-hidden="true">
            {marcada(opt) ? '✔' : ''}
          </span>
        {/if}
        <span class="opt-text">{multipla ? semCaixa(opt) : opt}</span>
      </button>
    {/each}
    {#if multipla && onSubmit}
      <!-- Marcar não envia. Sem este botão a única saída era Cancelar. -->
      <button
        class="option-btn option-btn--enviar"
        style="animation-delay: {options.length * 40}ms"
        onclick={onSubmit}
        disabled={marcadas === 0}
      >
        <span class="opt-num">➤</span>
        <span class="opt-text">{m.opcoes_enviar_marcadas({ n: marcadas })}</span>
      </button>
    {/if}
    <button
      class="option-btn option-btn--cancel"
      style="animation-delay: {(options.length + 1) * 40}ms"
      onclick={onCancel}
    >
      <span class="opt-num">✕</span>
      <span class="opt-text">{m.comum_cancelar()}</span>
    </button>
  </div>
</div>

<style>
  /* Mesmo material do cartão nativo (AskQuestionCard): os dois desenham a MESMA coisa — uma
     pergunta com opções — e antes um era um cartão e o outro, botões soltos sobre o papel de
     parede. Sem `--surface-raised` cru: quem tem papel de parede via retângulo chapado boiando. */
  .options-wrap {
    align-self: stretch;
    max-width: 600px;
    margin: var(--space-2) 0;
    background: var(--surface-raised);
    border: 1px solid var(--border-default);
    border-radius: var(--radius-lg);
    padding: var(--space-4) var(--space-4) var(--space-5);
  }

  .question {
    font-size: var(--text-lg);
    color: var(--text-primary);
    font-weight: 500;
    margin-bottom: var(--space-4);
    line-height: 1.4;
  }

  /* Pedido de permissao: chip + botoes com semantica visual (permitir/sempre/negar). */
  .perm-chip {
    display: inline-block;
    font-size: var(--text-xs);
    font-weight: 600;
    color: var(--accent);
    background: var(--accent-dim);
    border-radius: var(--radius-full);
    padding: 2px 10px;
    margin-bottom: var(--space-2);
  }
  .q-code {
    font-family: var(--font-mono);
    font-size: 0.85em;
    /* `--surface-inset`, não `--surface-raised`: este é o mesmo token do cartão que agora envolve a
       pergunta, e o trecho em code sumia dentro dele. */
    background: var(--surface-inset);
    padding: 2px 6px;
    border-radius: 4px;
    word-break: break-all;
  }
  .q-link { color: var(--accent); text-decoration: underline; word-break: break-all; }
  .option-btn--allow {
    background: var(--accent);
    border-color: var(--accent);
  }
  .option-btn--allow .opt-text, .option-btn--allow .opt-num { color: #fff; }
  .option-btn--allow:active { background: var(--accent-press); }
  .option-btn--always {
    background: var(--accent-dim);
    border-color: var(--accent);
  }
  .option-btn--always .opt-text { color: var(--accent); }
  .option-btn--deny {
    border-color: var(--error);
  }
  .option-btn--deny .opt-text, .option-btn--deny .opt-num { color: var(--error); }

  .options-list {
    display: flex;
    flex-direction: column;
    gap: var(--space-2);
  }

  .option-btn {
    width: 100%;
    min-height: 52px;
    /* Dentro do cartão, a opção precisa se destacar DELE: `--surface-inset` é o token de campo
       (o que recebe toque/entrada), e é ele que dá contraste sem virar segundo cartão. */
    background: var(--surface-inset);
    border: 1px solid var(--border-default);
    border-radius: var(--radius-lg);
    display: flex;
    align-items: center;
    gap: var(--space-3);
    padding: 0 var(--space-4);
    text-align: left;
    cursor: pointer;
    transition: background 180ms ease-out;
    animation: option-in 220ms ease-out both;
  }

  .option-btn:active {
    background: var(--bg-hover);
  }

  .option-btn--cancel {
    border-color: var(--error);
    color: var(--error);
  }

  /* Enviar as marcadas: é a ação POSITIVA da múltipla escolha, então tem o peso do acento —
     Cancelar continua sendo a saída, não o caminho. Sem marcação nenhuma ele desabilita: enviar
     zero opção é o mesmo que cancelar, e oferecer duas portas pro mesmo lugar confunde. */
  .option-btn--enviar {
    border-color: var(--accent);
    color: var(--accent);
    font-weight: 600;
  }
  .option-btn--enviar:disabled {
    opacity: 0.45;
    border-color: var(--border-subtle);
    color: var(--text-muted);
    font-weight: 400;
  }
  /* Caixinha: o estado vira desenho, e o rótulo fica só com o texto. */
  .opt-caixa {
    flex-shrink: 0;
    width: 18px; height: 18px;
    display: inline-flex; align-items: center; justify-content: center;
    border: 1px solid var(--border); border-radius: var(--radius-sm);
    font-size: 11px; line-height: 1;
  }
  .opt-caixa--on {
    background: var(--accent);
    border-color: var(--accent);
    color: var(--bg-base);
  }

  .opt-num {
    font-family: var(--font-mono);
    font-size: var(--text-sm);
    color: var(--text-secondary);
    flex-shrink: 0;
    min-width: 20px;
  }

  .option-btn--cancel .opt-num {
    color: var(--error);
  }

  .opt-text {
    font-size: var(--text-base);
    color: var(--text-primary);
  }

  .option-btn--cancel .opt-text {
    color: var(--error);
  }
</style>
