// mobile/app/config/worktrees.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { StyleSheet } from 'react-native-unistyles';
import { basename, fetchWorktreesForServer, getWorktreesForServer, mergedWorktreeBatch, relativeTime,
         WORKTREE_STALE_DAYS, worktreeAgeDays, worktreeIsAgent, worktreeReady, worktreesSizeTotal, worktreeState,
         type WorktreeRepo, type WorktreeStatus } from '@hangar/core';
import { Pagina } from '../../src/features/config/Pagina';
import { PageHeader, Pill } from '../../src/features/config/PageHeader';
import { SectionCard } from '../../src/features/config/SectionCard';
import { InfoNotice } from '../../src/features/config/InfoNotice';
import { useSettingsColors } from '../../src/features/config/colors';
import { WorktreeSheet } from '../../src/features/worktrees/WorktreeSheet';
import { WorktreeBatchSheet, type WorktreeBatch } from '../../src/features/worktrees/WorktreeBatchSheet';
import { putWorktreeStatus } from '../../src/features/worktrees/worktreeStatus';
import { displayTitle, SessionChips, sizeLabel, sizeSumLabel, STATE_TONE, stateLabel, useStateColor } from '../../src/features/worktrees/worktreeUi';
import { Chip } from '../../src/ui/Chip';
import { Icon } from '../../src/ui/Icon';
import { toast } from '../../src/ui/Toast';
import { useServers } from '../../src/stores/servers';
import { useSessions } from '../../src/stores/sessions';
import * as m from '../../src/paraglide/messages';

type Filter = 'todas' | 'uso' | 'dirty' | 'prontas' | 'paradas' | 'sem_branch';
const PENDING_REREAD_MS = 5000;
const PENDING_MAX_TRIES = 12;
const DISK_TOP = 5;

const stale = (w: WorktreeStatus) => (worktreeAgeDays(w) ?? 0) > WORKTREE_STALE_DAYS;
const MATCH: Record<Filter, (w: WorktreeStatus) => boolean> = {
  todas: () => true,
  uso: (w) => w.sessions.length > 0,
  dirty: (w) => w.dirty > 0,
  prontas: worktreeReady,
  paradas: stale,
  sem_branch: (w) => !w.branch,
};

export default function Worktrees() {
  const server = useServers((s) => s.active());
  // A leitura segue o id: o store troca o objeto do servidor a cada atualização da lista, e isso
  // não pode reler nem zerar a tela.
  const serverRef = useRef(server);
  serverRef.current = server;
  const serverId = server?.id ?? null;
  const geracao = useRef(0);
  const tentativas = useRef(0);
  const seq = useRef(0);
  const releitura = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [repos, setRepos] = useState<WorktreeRepo[] | null>(null);
  const [erro, setErro] = useState('');
  const [avisoFetch, setAvisoFetch] = useState<string[]>([]);
  const [demorando, setDemorando] = useState(false);
  const [atualizando, setAtualizando] = useState(false);
  const [aberta, setAberta] = useState<string | null>(null);
  const [filtro, setFiltro] = useState<Filter>('todas');
  const [agentesAbertos, setAgentesAbertos] = useState<Record<string, boolean>>({});
  // A confirmação congela o que a pessoa viu: o lote apaga essas e só essas.
  const [lote, setLote] = useState<WorktreeBatch | null>(null);
  const c = useSettingsColors();
  const cor = useStateColor();

  // Os chips de sessão leem o estado ao vivo da lista que o app já assina.
  useEffect(() => useSessions.getState().retain(), []);

  const carregar = useCallback(async (): Promise<WorktreeRepo[] | null> => {
    const alvo = serverRef.current;
    if (!alvo) return null;
    const g = geracao.current;
    // Só a resposta do pedido mais novo vale: uma releitura atrasada não desfaz o que um apagar já mostrou.
    const req = ++seq.current;
    const vale = () => g === geracao.current && req === seq.current;
    try {
      const r = await getWorktreesForServer(alvo);
      if (!vale()) return null;
      r.forEach((repo) => repo.worktrees.forEach((w) => putWorktreeStatus(alvo.id, w)));
      setRepos(r);
      setErro('');
      // O backend mede o disco em segundo plano, uma de cada vez: relê até os tamanhos chegarem, com teto.
      if (releitura.current) clearTimeout(releitura.current);
      releitura.current = null;
      const pendente = r.some((repo) => repo.worktrees.some((w) => w.size_pending));
      if (!pendente) tentativas.current = 0;
      else if (tentativas.current < PENDING_MAX_TRIES) {
        tentativas.current++;
        releitura.current = setTimeout(() => { if (g === geracao.current) void carregar(); }, PENDING_REREAD_MS);
      }
      setDemorando(pendente && tentativas.current >= PENDING_MAX_TRIES && !releitura.current);
      return r;
    } catch (e) {
      if (vale()) setErro(e instanceof Error ? e.message : String(e));
      return null;
    }
  }, []);

  const iniciar = useCallback(() => {
    const g = ++geracao.current;
    tentativas.current = 0;
    if (releitura.current) clearTimeout(releitura.current);
    setRepos(null); setErro(''); setAvisoFetch([]); setDemorando(false); setAberta(null); setLote(null); setAtualizando(false);
    const alvo = serverRef.current;
    if (!alvo) return;
    void (async () => {
      // Mostra o que já está no disco e só então busca o remoto, que pode demorar.
      const lidos = await carregar();
      if (!lidos || g !== geracao.current) return;
      setAtualizando(true);
      const res = await Promise.allSettled(lidos.map((r) => fetchWorktreesForServer(alvo, r.repo)));
      if (g !== geracao.current) return;
      setAtualizando(false);
      setAvisoFetch(res.flatMap((x, i) => {
        if (x.status !== 'rejected') return [];
        console.warn('worktrees: fetch falhou', lidos[i].repo, x.reason);
        return [m.worktrees_busca_remoto_falhou({ repo: basename(lidos[i].repo) })];
      }));
      await carregar();
    })();
  }, [carregar]);

  useEffect(() => {
    iniciar();
    return () => {
      // Invalida o que ainda está em voo: nada grava estado nem agenda releitura depois de sair.
      geracao.current++;
      if (releitura.current) clearTimeout(releitura.current);
    };
  }, [serverId, iniciar]);

  const recarregar = () => { tentativas.current = 0; void carregar(); };
  const loteApagado = (ficaram: string[]) => {
    if (ficaram.length) toast.erro(m.worktree_lote_nao_apagou({ nomes: ficaram.join(', ') }));
    recarregar();
  };

  const todas = useMemo(() => repos?.flatMap((r) => r.worktrees) ?? [], [repos]);
  const conta = (f: Filter) => todas.filter(MATCH[f]).length;
  const prontasTamanho = sizeSumLabel(todas.filter(worktreeReady));
  const emUsoNomes = todas.flatMap((w) => w.sessions);
  const contadores: { f: Filter; label: string; hint: string; color: string }[] = [
    { f: 'uso', label: m.worktrees_contador_em_uso(), color: cor('session'),
      hint: emUsoNomes.length ? emUsoNomes.join(' · ') : m.worktrees_contador_em_uso_vazio() },
    { f: 'dirty', label: m.worktrees_contador_nao_commitado(), color: cor('dirty'), hint: m.worktrees_contador_nao_commitado_dica() },
    { f: 'prontas', label: m.worktrees_contador_prontas(), color: cor('merged'), hint: m.worktrees_contador_prontas_dica({ tamanho: prontasTamanho }) },
    { f: 'paradas', label: m.worktrees_contador_paradas(), color: c.muted, hint: m.worktrees_contador_paradas_dica() },
  ];
  const filtros: { f: Filter; label: string }[] = [
    { f: 'todas', label: m.worktrees_filtro_todas() },
    { f: 'uso', label: m.worktrees_filtro_em_uso() },
    { f: 'dirty', label: m.worktrees_filtro_nao_commitado() },
    { f: 'prontas', label: m.worktrees_filtro_prontas() },
    { f: 'paradas', label: m.worktrees_filtro_paradas() },
    { f: 'sem_branch', label: m.worktrees_filtro_sem_branch() },
  ];
  const alternar = (f: Filter) => setFiltro((atual) => (atual === f ? 'todas' : f));

  const visiveis = repos?.map((r) => ({ r, ws: r.worktrees.filter(MATCH[filtro]) })).filter((x) => x.ws.length) ?? [];

  return (
    <Pagina>
      <PageHeader title={m.worktrees_titulo()} subtitle={atualizando ? m.worktrees_atualizando() : undefined} />
      {!server ? <InfoNotice text={m.maquinas_vazio()} /> : null}
      {server && repos === null && !erro ? <Text style={styles.muted}>{m.comum_carregando()}</Text> : null}
      {erro ? (
        <View style={styles.erroBloco}>
          <Text accessibilityRole="alert" style={styles.erro}>{m.worktrees_erro({ motivo: erro })}</Text>
          <Pill icon="RotateCw" label={m.busca_tentar_de_novo()} onPress={iniciar} />
        </View>
      ) : null}
      {avisoFetch.map((t) => <Text key={t} accessibilityRole="alert" style={styles.aviso}>{t}</Text>)}
      {repos && repos.length === 0 ? <InfoNotice text={m.worktrees_vazio()} /> : null}
      {server && repos?.length ? (
        <>
          <View style={styles.grade}>
            {contadores.map((k) => {
              const on = filtro === k.f;
              return (
                <Pressable key={k.f} onPress={() => alternar(k.f)} accessibilityRole="button" accessibilityState={{ selected: on }}
                  accessibilityLabel={`${k.label}: ${conta(k.f)}`}
                  style={({ pressed }) => [styles.contador, { borderColor: on ? k.color : c.border, backgroundColor: c.inset },
                    pressed && { opacity: 0.7 }]}>
                  <View style={styles.contadorTopo}>
                    <View style={[styles.ponto, { backgroundColor: k.color }]} />
                    <Text style={[styles.contadorLabel, { color: c.muted }]} numberOfLines={2}>{k.label}</Text>
                  </View>
                  <Text style={[styles.contadorN, { color: c.text }]}>{conta(k.f)}</Text>
                  <Text style={[styles.contadorHint, { color: c.faint }]} numberOfLines={2}>{k.hint}</Text>
                </Pressable>
              );
            })}
          </View>
          <Disco todas={todas} onPick={setAberta} demorando={demorando} onRetry={recarregar} />
          <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filtros}>
            {filtros.map((x) => {
              const on = filtro === x.f;
              return (
                <Pressable key={x.f} onPress={() => setFiltro(x.f)} accessibilityRole="button" accessibilityState={{ selected: on }}
                  hitSlop={{ top: 5, bottom: 5 }}
                  style={[styles.filtro, { borderColor: on ? c.borderStrong : c.border }, on && { backgroundColor: c.hover }]}>
                  <Text style={[styles.filtroTxt, { color: on ? c.text : c.muted }]}>{x.label}</Text>
                  <Text style={[styles.filtroN, { color: c.faint }]}>{conta(x.f)}</Text>
                </Pressable>
              );
            })}
          </ScrollView>
          {!visiveis.length ? <InfoNotice text={m.worktrees_filtro_vazio()} /> : null}
          {visiveis.map(({ r, ws }) => {
            const b = mergedWorktreeBatch(r);
            // Mesmo número do contador "Prontas pra apagar"; o lote só aparece sozinho quando não há prontas.
            const prontas = r.worktrees.filter(worktreeReady);
            const limpar = prontas.length ? prontas : b.deletable;
            const principais = ws.filter((w) => !worktreeIsAgent(w));
            const agentes = ws.filter(worktreeIsAgent);
            // Com filtro ligado o grupo abre sozinho: o que casou não pode ficar escondido.
            const agentesVisiveis = filtro !== 'todas' || !!agentesAbertos[r.repo];
            const maisRecente = Math.max(0, ...agentes.map((w) => w.last_commit?.at ?? w.created_at ?? 0));
            const principal = r.worktrees.find((w) => w.main_branch)?.main_branch;
            return (
              <SectionCard
                key={r.repo}
                icon="GitBranch"
                title={basename(r.repo)}
                subtitle={[m.worktree_repo_resumo({ n: r.worktrees.length, tamanho: sizeSumLabel(r.worktrees) }),
                  ...(principal ? [m.worktree_repo_principal({ branch: principal })] : [])].join(' · ')}
              >
                {b.deletable.length ? (
                  <View style={[styles.limpar, { borderTopColor: c.border }]}>
                    <Pill icon="Trash2" onPress={() => setLote({ repo: r.repo, ...b })}
                      label={m.worktree_limpar_mescladas({ n: limpar.length, tamanho: sizeSumLabel(limpar) })} />
                  </View>
                ) : null}
                {principais.map((w) => <Linha key={w.path} w={w} serverId={server.id} onPick={setAberta} />)}
                {agentes.length ? (
                  <>
                    <Pressable onPress={() => setAgentesAbertos((o) => ({ ...o, [r.repo]: !o[r.repo] }))}
                      accessibilityRole="button" accessibilityState={{ expanded: agentesVisiveis }}
                      style={[styles.grupo, { borderTopColor: c.border }]}>
                      <Icon name={agentesVisiveis ? 'ChevronDown' : 'ChevronRight'} size={16} color={c.muted} />
                      <View style={styles.flex}>
                        <Text style={[styles.titulo, { color: c.text }]}>{m.worktree_subagentes()}  <Text style={{ color: c.faint }}>{agentes.length}</Text></Text>
                        {maisRecente ? (
                          <Text style={[styles.meta, { color: c.faint }]}>{m.worktree_subagentes_dica({ quando: relativeTime(maisRecente) })}</Text>
                        ) : null}
                      </View>
                    </Pressable>
                    {agentesVisiveis ? agentes.map((w) => <Linha key={w.path} w={w} serverId={server.id} onPick={setAberta} />) : null}
                  </>
                ) : null}
              </SectionCard>
            );
          })}
          <Text style={[styles.legenda, { color: c.faint }]}>{m.worktrees_legenda_commits()}</Text>
        </>
      ) : null}
      <WorktreeSheet server={server} path={aberta} onClose={() => setAberta(null)} onDeleted={recarregar} />
      <WorktreeBatchSheet server={server} batch={lote} onClose={() => setLote(null)} onDeleted={loteApagado} />
    </Pagina>
  );
}

function Linha({ w, serverId, onPick }: { w: WorktreeStatus; serverId: string; onPick: (path: string) => void }) {
  const c = useSettingsColors();
  const k = worktreeState(w);
  const idade = worktreeAgeDays(w);
  const atividade = relativeTime(w.last_commit?.at ?? w.created_at);
  const titulo = displayTitle(w);
  return (
    <View style={[styles.linha, { borderTopColor: c.border }]}>
      <Pressable onPress={() => onPick(w.path)} accessibilityRole="button" accessibilityLabel={`${titulo}, ${stateLabel(k)}`}
        style={({ pressed }) => [styles.linhaCorpo, pressed && { opacity: 0.6 }]}>
        <View style={styles.linhaTopo}>
          <Text style={[styles.titulo, styles.flex, { color: c.text }]} numberOfLines={1}>{titulo}</Text>
          <Text style={[styles.meta, { color: c.muted }]}>{sizeLabel(w)}</Text>
        </View>
        <View style={styles.linhaEstado}>
          <Chip tone={STATE_TONE[k]}>{stateLabel(k)}</Chip>
          {idade != null && stale(w) ? <Text style={[styles.meta, { color: c.faint }]}>{m.worktree_parada_dias({ n: idade })}</Text> : null}
        </View>
        <Text style={[styles.mono, { color: c.muted }]} numberOfLines={1}>
          {w.branch ?? m.worktree_sem_branch_rotulo()} ← {w.base ?? ''}
        </Text>
        {w.last_commit ? <Text style={[styles.meta, { color: c.muted }]} numberOfLines={1}>{w.last_commit.subject}</Text> : null}
        {w.degraded ? <Text style={styles.aviso}>{m.worktree_leitura_incompleta()}</Text> : null}
        <Text style={[styles.meta, { color: c.faint }]} numberOfLines={1}>
          {[`↑${w.ahead} ↓${w.behind ?? 0}`,
            w.dirty ? m.worktree_n_nao_commitados({ n: w.dirty }) : m.worktree_limpa(),
            ...(atividade ? [atividade] : [])].join(' · ')}
        </Text>
      </Pressable>
      <SessionChips serverId={serverId} names={w.sessions} />
    </View>
  );
}

function Disco({ todas, onPick, demorando, onRetry }: { todas: WorktreeStatus[]; onPick: (path: string) => void; demorando: boolean; onRetry: () => void }) {
  const c = useSettingsColors();
  const cor = useStateColor();
  const medidas = todas.filter((w) => (w.size ?? 0) > 0).sort((a, b) => (b.size ?? 0) - (a.size ?? 0));
  const pendente = todas.some((w) => w.size_pending);
  const prontas = todas.filter(worktreeReady);
  const maior = medidas[0]?.size ?? 1;
  const topo = medidas.slice(0, DISK_TOP);
  const resto = medidas.slice(DISK_TOP);
  const legenda = [
    { k: 'merged', label: m.worktrees_filtro_prontas() },
    { k: 'dirty', label: m.worktrees_filtro_nao_commitado() },
    { k: 'session', label: m.worktrees_filtro_em_uso() },
    { k: 'active', label: m.worktree_estado_andamento() },
    { k: 'detached', label: m.worktrees_filtro_sem_branch() },
  ] as const;
  return (
    <SectionCard icon="HardDrive" title={m.worktrees_disco_titulo()}
      subtitle={[m.worktrees_disco_resumo({ total: sizeSumLabel(todas), n: medidas.length }),
        ...(worktreesSizeTotal(prontas).bytes ? [m.worktrees_disco_libera({ tamanho: sizeSumLabel(prontas) })] : []),
        ...(pendente ? [demorando ? m.worktrees_disco_demorando() : m.worktrees_disco_calculando()] : [])].join(' · ')}>
      <View style={[styles.disco, { borderTopColor: c.border }]}>
        {pendente && demorando ? (
          <View style={styles.erroBloco}><Pill icon="RotateCw" label={m.busca_tentar_de_novo()} onPress={onRetry} /></View>
        ) : null}
        {medidas.length ? (
          <View style={[styles.barra, { backgroundColor: c.inset }]}>
            {medidas.map((w) => <View key={w.path} style={{ flexGrow: w.size ?? 0, backgroundColor: cor(worktreeState(w)) }} />)}
          </View>
        ) : null}
        {topo.map((w) => {
          const k = worktreeState(w);
          return (
            <Pressable key={w.path} onPress={() => onPick(w.path)} accessibilityRole="button"
              accessibilityLabel={`${displayTitle(w)}, ${sizeLabel(w)}, ${stateLabel(k)}`}
              style={({ pressed }) => [styles.discoLinha, pressed && { opacity: 0.6 }]}>
              <View style={styles.linhaTopo}>
                <Text style={[styles.meta, styles.flex, { color: c.text }]} numberOfLines={1}>{displayTitle(w)}</Text>
                <Text style={[styles.meta, { color: c.muted }]}>{sizeLabel(w)}</Text>
              </View>
              <View style={[styles.trilho, { backgroundColor: c.inset }]}>
                <View style={{ width: `${Math.max(1, Math.round(((w.size ?? 0) / maior) * 100))}%` as const, height: '100%', borderRadius: 3, backgroundColor: cor(k) }} />
              </View>
            </Pressable>
          );
        })}
        {resto.length ? (
          <View style={[styles.linhaTopo, styles.discoLinha]}>
            <Text style={[styles.meta, styles.flex, { color: c.muted }]}>{m.worktrees_disco_outras({ n: resto.length })}</Text>
            <Text style={[styles.meta, { color: c.muted }]}>{sizeSumLabel(resto)}</Text>
          </View>
        ) : null}
        <View style={styles.legendaLinha}>
          {legenda.map((l) => (
            <View key={l.k} style={styles.legendaItem}>
              <View style={[styles.ponto, { backgroundColor: cor(l.k) }]} />
              <Text style={[styles.meta, { color: c.faint }]}>{l.label}</Text>
            </View>
          ))}
        </View>
      </View>
    </SectionCard>
  );
}

const styles = StyleSheet.create((theme) => ({
  muted: { fontSize: theme.base.text.sm, color: theme.tokens.text.muted, paddingHorizontal: 4 },
  erro: { fontSize: theme.base.text.sm, color: theme.tokens.status.error, paddingHorizontal: 4 },
  erroBloco: { gap: 8, alignItems: 'flex-start' },
  aviso: { fontSize: theme.base.text.xs, color: theme.tokens.status.warning, paddingHorizontal: 4 },
  flex: { flex: 1, minWidth: 0 },
  grade: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  contador: { flexBasis: '45%', flexGrow: 1, borderWidth: 1, borderRadius: 12, padding: 12, gap: 4 },
  contadorTopo: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  contadorLabel: { flex: 1, fontSize: theme.base.text.xxs },
  contadorN: { fontSize: theme.base.text.xl, fontWeight: '600', fontVariant: ['tabular-nums'] },
  contadorHint: { fontSize: theme.base.text.xxxs },
  ponto: { width: 8, height: 8, borderRadius: 4 },
  filtros: { gap: 8, paddingHorizontal: 2 },
  filtro: { flexDirection: 'row', alignItems: 'center', gap: 6, height: 34, paddingHorizontal: 12, borderWidth: 1, borderRadius: 9999 },
  filtroTxt: { fontSize: theme.base.text.xs, fontWeight: '500' },
  filtroN: { fontSize: theme.base.text.xxs, fontVariant: ['tabular-nums'] },
  limpar: { borderTopWidth: 1, paddingVertical: 10, paddingHorizontal: 16, flexDirection: 'row' },
  linha: { borderTopWidth: 1, paddingVertical: 12, paddingHorizontal: 16, gap: 8 },
  linhaCorpo: { gap: 4 },
  linhaTopo: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  linhaEstado: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  titulo: { fontSize: theme.base.text.sm, fontWeight: '500' },
  meta: { fontSize: theme.base.text.xs, fontVariant: ['tabular-nums'] },
  mono: { fontSize: theme.base.text.xxs, fontFamily: theme.base.fontMono },
  grupo: { borderTopWidth: 1, paddingVertical: 12, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 10 },
  disco: { borderTopWidth: 1, paddingVertical: 12, paddingHorizontal: 16, gap: 10 },
  barra: { flexDirection: 'row', height: 10, borderRadius: 5, overflow: 'hidden', gap: 1 },
  discoLinha: { gap: 4, minHeight: 44, justifyContent: 'center' },
  trilho: { height: 6, borderRadius: 3, overflow: 'hidden' },
  legendaLinha: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, paddingTop: 2 },
  legendaItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  legenda: { fontSize: theme.base.text.xxs, paddingHorizontal: 4 },
}));

// frontend/src/screens/Worktrees.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import { basename, deleteMergedWorktreesForServer, fetchWorktreesForServer, getWorktreesForServer,
           mergedWorktreeBatch, relativeTime, worktreeAgeDays, worktreeIsAgent, worktreeReady, worktreeState,
           worktreeTitle, WORKTREE_STALE_DAYS, type WorktreeRepo, type WorktreeState, type WorktreeStatus } from '@hangar/core';
  import BottomSheet from '../components/BottomSheet.svelte';
  import Spinner from '../components/Spinner.svelte';
  import WorktreeSheet from '../components/WorktreeSheet.svelte';
  import { listOwnServers, onServersChanged, type Server } from '../lib/auth';
  import { sessionsStore } from '../lib/sessionsStore.svelte';
  import { worktreeStatus } from '../lib/worktreeStatus.svelte';
  import { goToSession, sessionStateLabel, worktreeSizeLabel, worktreesSizeBytes as somaTamanho, worktreesSizeSum,
           worktreeStateColor, worktreeStateLabel } from '../lib/worktreeView';
  import * as m from '../paraglide/messages';

  let { onBack }: { onBack?: () => void } = $props();
  let servidores = $state<Server[]>(listOwnServers());
  $effect(() => onServersChanged(() => { servidores = listOwnServers(); }));
  // Estado vivo das sessões nas fichas: o mesmo stream da lista, nunca um pedido por linha.
  $effect(() => {
    sessionsStore.retain();
    return () => sessionsStore.release();
  });

  type Bloco = { servidor: Server; repos: WorktreeRepo[]; erro: string };
  let blocos = $state<Bloco[]>([]);
  let carregando = $state(true);
  let atualizando = $state(false);
  let aberta = $state<{ servidor: Server; path: string } | null>(null);
  let geracao = 0;

  async function carregar() {
    const meu = ++geracao;
    carregando = blocos.length === 0;
    const out = await Promise.all(servidores.map(async (s) => {
      try {
        const repos = await getWorktreesForServer(s);
        for (const r of repos) for (const w of r.worktrees) worktreeStatus.put(s.id, w);
        return { servidor: s, repos, erro: '' };
      } catch (e) { return { servidor: s, repos: [], erro: e instanceof Error ? e.message : String(e) }; }
    }));
    if (meu !== geracao) return;
    blocos = out;
    carregando = false;
  }

  // Primeiro mostra o que o disco já sabe; o fetch dos remotos (lento) vem depois e relê.
  // Por `serverId::repo`: o fetch do remoto que falhou deixa mesclada/atrasada velhas, e isso aparece.
  let erroRemoto = $state<Record<string, true>>({});
  async function atualizar() {
    releituras = 0;
    atualizando = true;
    const alvos = blocos.flatMap((b) => b.repos.map((r) => ({ b, repo: r.repo })));
    const res = await Promise.allSettled(alvos.map(({ b, repo }) => fetchWorktreesForServer(b.servidor, repo)));
    const falhas: Record<string, true> = {};
    res.forEach((x, i) => { if (x.status === 'rejected') falhas[chaveLote(alvos[i].b, alvos[i].repo)] = true; });
    erroRemoto = falhas;
    atualizando = false;
    await carregar();
  }

  // O backend mede o tamanho em segundo plano, uma pasta por vez: relê a cada 5 s enquanto houver
  // medida pendente, com teto para não ficar lendo para sempre se a medição travar.
  const medindo = $derived(blocos.some((b) => b.repos.some((r) => r.worktrees.some((w) => w.size_pending))));
  const MAX_RELEITURAS = 12;
  let releituras = $state(0);
  const demorando = $derived(medindo && releituras >= MAX_RELEITURAS);
  $effect(() => {
    blocos;   // cada leitura nova reagenda a próxima
    if (!medindo) { releituras = 0; return; }   // conta só releituras seguidas
    if (untrack(() => releituras) >= MAX_RELEITURAS) return;
    const t = setTimeout(() => { releituras++; void carregar(); }, 5000);
    return () => clearTimeout(t);
  });
  function tentarMedirDeNovo() {
    releituras = 0;
    void carregar();
  }

  // Por `serverId::repo`: o lote em andamento (botão desligado) e o aviso dele, que não é de leitura.
  let loteAndando = $state<string | null>(null);
  let erroLote = $state<Record<string, string>>({});
  const chaveLote = (b: Bloco, repo: string) => `${b.servidor.id}::${repo}`;

  // A confirmação congela o que a pessoa viu: o lote apaga essas e só essas.
  type Confirmacao = { bloco: Bloco; repo: string; deletable: WorktreeStatus[]; blocked: WorktreeStatus[] };
  let confirmando = $state<Confirmacao | null>(null);

  function pedirLote(b: Bloco, r: WorktreeRepo) {
    confirmando = { bloco: b, repo: r.repo, ...mergedWorktreeBatch(r) };
  }

  async function apagarMescladas() {
    if (!confirmando) return;
    const { bloco: b, repo, deletable } = confirmando;
    const k = chaveLote(b, repo);
    confirmando = null;
    loteAndando = k;
    delete erroLote[k];
    try {
      const removidas = await deleteMergedWorktreesForServer(b.servidor, repo, deletable);
      for (const p of removidas) worktreeStatus.drop(b.servidor.id, p);
      const ficaram = deletable.filter((w) => !removidas.includes(w.path));
      if (ficaram.length) erroLote[k] = m.worktree_lote_nao_apagou({ nomes: ficaram.map((w) => basename(w.path)).join(', ') });
    } catch (e) {
      erroLote[k] = e instanceof Error ? e.message : String(e);
    } finally {
      loteAndando = null;
    }
    await carregar();
  }

  // Mesma chave do Orq: lista recarregada com os mesmos servidores não refaz a leitura nem zera a tela.
  const chaveServidores = $derived(servidores.map((s) => `${s.id}|${s.baseUrl}|${s.token}`).join('\n'));
  $effect(() => { chaveServidores; untrack(() => { void carregar().then(atualizar); }); });

  const vazio = $derived(!carregando && blocos.every((b) => !b.erro && b.repos.length === 0));

  // ── Filtros e contadores ──────────────────────────────────────────────────
  type Filtro = 'todas' | 'uso' | 'dirty' | 'prontas' | 'paradas' | 'sem_branch';
  let filtro = $state<Filtro>('todas');
  const parada = (w: WorktreeStatus) => (worktreeAgeDays(w) ?? 0) > WORKTREE_STALE_DAYS;
  const passa: Record<Filtro, (w: WorktreeStatus) => boolean> = {
    todas: () => true,
    uso: (w) => w.sessions.length > 0,
    dirty: (w) => w.dirty > 0,
    prontas: worktreeReady,
    paradas: parada,
    sem_branch: (w) => !w.branch,
  };
  type Item = { servidor: Server; w: WorktreeStatus; estado: WorktreeState };
  const todas = $derived<Item[]>(blocos.flatMap((b) => b.repos.flatMap((r) =>
    r.worktrees.map((w) => ({ servidor: b.servidor, w, estado: worktreeState(w) })))));
  const conta = (f: Filtro) => todas.filter((i) => passa[f](i.w)).length;
  const prontas = $derived(todas.filter((i) => worktreeReady(i.w)).map((i) => i.w));
  const liberaProntas = $derived(somaTamanho(prontas));
  const nomesEmUso = $derived([...new Set(todas.flatMap((i) => i.w.sessions))].join(' · '));

  const contadores = $derived<{ f: Filtro; rotulo: string; dica: string; cor: string }[]>([
    { f: 'uso', rotulo: m.worktrees_contador_em_uso(), dica: nomesEmUso || m.worktrees_contador_em_uso_vazio(), cor: 'var(--accent)' },
    { f: 'dirty', rotulo: m.worktrees_contador_nao_commitado(), dica: m.worktrees_contador_nao_commitado_dica(), cor: 'var(--warning)' },
    { f: 'prontas', rotulo: m.worktrees_contador_prontas(), dica: m.worktrees_contador_prontas_dica({ tamanho: worktreesSizeSum(prontas) }), cor: 'var(--success)' },
    { f: 'paradas', rotulo: m.worktrees_contador_paradas(), dica: m.worktrees_contador_paradas_dica(), cor: 'var(--text-muted)' },
  ]);
  const filtros = $derived<{ f: Filtro; rotulo: string }[]>([
    { f: 'todas', rotulo: m.worktrees_filtro_todas() },
    { f: 'uso', rotulo: m.worktrees_filtro_em_uso() },
    { f: 'dirty', rotulo: m.worktrees_filtro_nao_commitado() },
    { f: 'prontas', rotulo: m.worktrees_filtro_prontas() },
    { f: 'paradas', rotulo: m.worktrees_filtro_paradas() },
    { f: 'sem_branch', rotulo: m.worktrees_filtro_sem_branch() },
  ]);

  // ── Disco ─────────────────────────────────────────────────────────────────
  const TOPO = 6;
  const porTamanho = $derived(todas.filter((i) => (i.w.size ?? 0) > 0).sort((a, b) => (b.w.size ?? 0) - (a.w.size ?? 0)));
  const discoTotal = $derived(worktreesSizeSum(todas.map((i) => i.w)));
  const discoResto = $derived(porTamanho.slice(TOPO));
  const legenda: { e: WorktreeState; rotulo: () => string }[] = [
    { e: 'merged', rotulo: m.worktrees_filtro_prontas },
    { e: 'dirty', rotulo: m.worktrees_filtro_nao_commitado },
    { e: 'session', rotulo: m.worktrees_filtro_em_uso },
    { e: 'active', rotulo: m.worktree_estado_andamento },
    { e: 'detached', rotulo: m.worktrees_filtro_sem_branch },
  ];

  // Subagentes recolhidos por repositório; com filtro ligado, abertos (é o que a pessoa procura).
  let subAbertos = $state<Record<string, boolean>>({});

  function atividade(w: WorktreeStatus): string {
    const d = worktreeAgeDays(w);
    if (d === null) return '—';
    return d >= 1 ? m.worktree_dias_atras({ n: d }) : relativeTime(w.last_commit?.at ?? w.created_at);
  }
  const estadoSessao = (s: Server, nome: string) => sessionsStore.rows.find((r) => r.serverId === s.id && r.name === nome)?.state;
</script>

{#snippet ficha(servidor: Server, w: WorktreeStatus)}
  {@const e = worktreeState(w)}
  {@const dias = worktreeAgeDays(w)}
  <li class="ficha">
    <div class="ficha-topo">
      <button type="button" class="abrir" onclick={() => (aberta = { servidor, path: w.path })}>{worktreeTitle(w)}</button>
      <span class="tam" class:aviso={w.size_error}>{worktreeSizeLabel(w)}</span>
    </div>
    <div class="chips">
      <span class="chip" style:--cor={worktreeStateColor[e]}>{worktreeStateLabel[e]()}</span>
      {#if parada(w) && dias !== null}<span class="chip" style:--cor="var(--warning)">{m.worktree_parada_dias({ n: dias })}</span>{/if}
    </div>
    {#if w.sessions.length}
      <div class="sessoes">
        {#each w.sessions as nome (nome)}
          {@const est = estadoSessao(servidor, nome)}
          <button type="button" class="sessao" aria-label={m.worktree_ir_sessao_nome({ nome })} onclick={() => goToSession(servidor.id, nome)}>
            <span class="ponto" class:ponto--vivo={est === 'working'} class:ponto--espera={est === 'awaiting_input'} aria-hidden="true"></span>
            <span class="sessao-nome">{nome}</span>
            {#if est}<span class="muted">{sessionStateLabel(est)}</span>{/if}
            <span aria-hidden="true">→</span>
          </button>
        {/each}
      </div>
    {/if}
    <div class="mono"><span>{w.branch ?? m.worktree_sem_branch_rotulo()}</span><span class="muted"> ← {w.base ?? '—'}</span></div>
    {#if w.degraded}<p class="aviso" role="note">{m.worktree_leitura_incompleta()}</p>{/if}
    {#if w.last_commit}<div class="assunto">{w.last_commit.subject}</div>{/if}
    <div class="metricas">
      <span class="mono">↑{w.ahead} ↓{w.behind ?? 0}</span>
      <span class:aviso={w.dirty > 0} class:muted={!w.dirty}>{w.dirty ? m.worktree_n_nao_commitados({ n: w.dirty }) : m.worktree_limpa()}</span>
      <span class="muted">{atividade(w)}</span>
      {#if w.created_at}<span class="muted">{m.worktree_criada({ quando: relativeTime(w.created_at) })}</span>{/if}
    </div>
  </li>
{/snippet}

<div class="wt">
  <header class="topo">
    {#if onBack}<button class="voltar" onclick={onBack} aria-label={m.orq_voltar()}>←</button>{/if}
    <h1>{m.worktrees_titulo()}</h1>
    {#if atualizando}<span class="muted">{m.worktrees_atualizando()}</span>{/if}
  </header>
  {#if carregando}
    <div class="centro"><Spinner /></div>
  {:else if vazio}
    <p class="vazio">{m.worktrees_vazio()}</p>
  {:else}
    {#each blocos as b (b.servidor.id)}
      {#if b.erro}<p class="erro" role="alert">{b.servidor.label}: {m.worktrees_erro({ motivo: b.erro })}</p>{/if}
    {/each}

    {#if todas.length}
      <section class="contadores">
        {#each contadores as c (c.f)}
          <button type="button" class="contador" class:on={filtro === c.f} style:--cor={c.cor} aria-pressed={filtro === c.f}
                  onclick={() => (filtro = filtro === c.f ? 'todas' : c.f)}>
            <span class="contador-rotulo">{c.rotulo}</span>
            <span class="contador-n">{conta(c.f)}</span>
            <span class="contador-dica">{c.dica}</span>
          </button>
        {/each}
      </section>

      <section class="disco">
        <h2>{m.worktrees_disco_titulo()}</h2>
        {#if demorando}
          <p class="aviso">{m.worktrees_disco_demorando()}
            <button type="button" class="tentar" onclick={tentarMedirDeNovo}>{m.busca_tentar_de_novo()}</button></p>
        {:else if medindo}<p class="muted">{m.worktrees_disco_calculando()}</p>{/if}
        {#if porTamanho.length}
          <p class="muted">{m.worktrees_disco_resumo({ total: discoTotal, n: porTamanho.length })}
            {#if liberaProntas} · <span class="libera">{m.worktrees_disco_libera({ tamanho: worktreesSizeSum(prontas) })}</span>{/if}</p>
          <div class="barra" aria-hidden="true">
            {#each porTamanho as i (i.servidor.id + i.w.path)}<span style:flex-grow={String(i.w.size)} style:background={worktreeStateColor[i.estado]}></span>{/each}
          </div>
          <ul class="disco-linhas">
            {#each porTamanho.slice(0, TOPO) as i (i.servidor.id + i.w.path)}
              <li>
                <button type="button" class="disco-linha" onclick={() => (aberta = { servidor: i.servidor, path: i.w.path })}>
                  <span class="ponto" style:background={worktreeStateColor[i.estado]} aria-hidden="true"></span>
                  <span class="disco-nome">{worktreeTitle(i.w)}</span>
                  <span class="muted">{worktreeStateLabel[i.estado]()}</span>
                  <span class="tam">{worktreeSizeLabel(i.w)}</span>
                </button>
              </li>
            {/each}
            {#if discoResto.length}
              <li class="disco-linha disco-linha--resto">
                <span class="ponto" aria-hidden="true"></span>
                <span class="disco-nome">{m.worktrees_disco_outras({ n: discoResto.length })}</span>
                <span class="tam">{worktreesSizeSum(discoResto.map((i) => i.w))}</span>
              </li>
            {/if}
          </ul>
          <div class="legenda">
            {#each legenda as l (l.e)}<span><span class="ponto" style:background={worktreeStateColor[l.e]} aria-hidden="true"></span>{l.rotulo()}</span>{/each}
          </div>
        {/if}
      </section>

      <div class="filtros" role="toolbar">
        {#each filtros as f (f.f)}
          <button type="button" class="filtro" class:on={filtro === f.f} aria-pressed={filtro === f.f} onclick={() => (filtro = f.f)}>
            {f.rotulo}<span class="filtro-n">{conta(f.f)}</span>
          </button>
        {/each}
      </div>
    {/if}

    {@const algumVisivel = todas.some((i) => passa[filtro](i.w))}
    {#if todas.length && !algumVisivel}<p class="vazio">{m.worktrees_filtro_vazio()}</p>{/if}

    {#each blocos as b (b.servidor.id)}
      {#each b.repos as r (r.repo)}
        {@const visiveis = r.worktrees.filter(passa[filtro])}
        {@const principais = visiveis.filter((w) => !worktreeIsAgent(w))}
        {@const agentes = visiveis.filter(worktreeIsAgent)}
        {@const lote = mergedWorktreeBatch(r)}
        {@const k = chaveLote(b, r.repo)}
        {@const subAberto = filtro !== 'todas' || !!subAbertos[k]}
        {@const principal = r.worktrees.find((w) => w.main_branch)?.main_branch}
        {#if visiveis.length || erroLote[k] || erroRemoto[k]}
          <section class="repo">
            <div class="repo-topo">
              <h2>{basename(r.repo)}{servidores.length > 1 ? ` · ${b.servidor.label}` : ''}</h2>
              {#if principal}<span class="muted">{m.worktree_repo_principal({ branch: principal })}</span>{/if}
              <span class="muted">{m.worktree_repo_resumo({ n: r.worktrees.length, tamanho: worktreesSizeSum(r.worktrees) })}</span>
            </div>
            {#if lote.deletable.length}
              <button type="button" class="lote" disabled={loteAndando === k} onclick={() => pedirLote(b, r)}>
                {#if loteAndando === k}<Spinner />{/if}
                {m.worktree_limpar_mescladas({ n: lote.deletable.length, tamanho: worktreesSizeSum(lote.deletable) })}
              </button>
            {/if}
            {#if erroLote[k]}<p class="erro" role="alert">{erroLote[k]}</p>{/if}
            {#if erroRemoto[k]}<p class="aviso" role="alert">{m.worktrees_busca_remoto_falhou({ repo: basename(r.repo) })}</p>{/if}
            <ul class="fichas">
              {#each principais as w (w.path)}{@render ficha(b.servidor, w)}{/each}
            </ul>
            {#if agentes.length}
              {@const recente = Math.max(...agentes.map((w) => w.last_commit?.at ?? w.created_at ?? 0))}
              <button type="button" class="subagentes" aria-expanded={subAberto} onclick={() => (subAbertos[k] = !subAbertos[k])}>
                <span class="seta" class:seta--aberta={subAberto} aria-hidden="true">›</span>
                <span class="sub-titulo">{m.worktree_subagentes()} <span class="filtro-n">{agentes.length}</span></span>
                {#if recente}<span class="muted">{m.worktree_subagentes_dica({ quando: relativeTime(recente) })}</span>{/if}
              </button>
              {#if subAberto}
                <ul class="fichas">
                  {#each agentes as w (w.path)}{@render ficha(b.servidor, w)}{/each}
                </ul>
              {/if}
            {/if}
          </section>
        {/if}
      {/each}
    {/each}
    {#if todas.length}<p class="muted legenda-commits">{m.worktrees_legenda_commits()}</p>{/if}
  {/if}
</div>
{#if aberta}
  <WorktreeSheet open={true} server={aberta.servidor} path={aberta.path} onClose={() => (aberta = null)} onDeleted={carregar} />
{/if}
{#if confirmando}
  {@const libera = somaTamanho(confirmando.deletable)}
  <BottomSheet open={true} onClose={() => (confirmando = null)} ariaLabel={m.worktree_lote_titulo({ n: confirmando.deletable.length })}>
    <div class="sheet">
      <h2 class="title">{m.worktree_lote_titulo({ n: confirmando.deletable.length })}</h2>
      {#if libera}<p class="libera">{m.worktree_libera({ tamanho: worktreesSizeSum(confirmando.deletable) })}</p>{/if}
      <ul class="itens">
        {#each confirmando.deletable as w (w.path)}
          <li>
            <span class="nome">{basename(w.path)}</span>
            {#if w.dirty || w.ignored.length}
              <span class="aviso">{m.worktree_apagar_perde()}</span>
              <ul class="perde">
                {#if w.dirty}<li>{m.worktree_nao_commitados({ n: w.dirty })}</li>{/if}
                {#each w.ignored as f (f)}<li>{f}</li>{/each}
              </ul>
            {:else}
              <span class="muted">{m.worktree_lote_nada_perde()}</span>
            {/if}
          </li>
        {/each}
      </ul>
      {#if confirmando.blocked.length}
        <p class="aviso">{m.worktree_lote_ficam()}</p>
        <ul class="itens">
          {#each confirmando.blocked as w (w.path)}
            <li>
              <span class="nome">{basename(w.path)}</span>
              <span class="muted">{w.sessions.length ? m.worktree_sessao_aberta({ nomes: w.sessions.join(', ') }) : m.worktree_lote_leitura_falhou()}</span>
            </li>
          {/each}
        </ul>
      {/if}
      <div class="acoes">
        <button type="button" class="cancelar" onclick={() => (confirmando = null)}>{m.comum_cancelar()}</button>
        <button type="button" class="apagar" onclick={apagarMescladas}>{m.worktree_lote_confirmar()}</button>
      </div>
    </div>
  </BottomSheet>
{/if}

<style>
  .wt { display: flex; flex-direction: column; gap: 12px; height: 100%; overflow-y: auto; padding: 12px 16px 32px; }
  .topo { display: flex; align-items: center; gap: 8px; }
  .topo h1 { font-size: 1.15rem; margin: 0; flex: 1; }
  .voltar { background: none; border: 0; font-size: 1.2rem; min-width: 40px; min-height: 40px; color: inherit; }
  h2 { font-size: 0.95rem; margin: 0; }
  .muted { color: var(--text-muted); font-size: 0.85rem; }
  .mono { font-family: var(--font-mono); font-size: 0.82rem; overflow-wrap: anywhere; }
  .aviso { color: var(--warning-text); font-size: 0.85rem; }
  .libera { color: var(--success-text); }
  .erro { color: var(--error); margin: 0; }
  .vazio { color: var(--text-muted); text-align: center; padding: 32px 0; margin: 0; }
  .centro { display: flex; justify-content: center; padding: 32px; }
  .ponto { width: 8px; height: 8px; border-radius: 50%; flex: none; background: var(--text-muted); display: inline-block; }
  .ponto--vivo { background: var(--success); }
  .ponto--espera { background: var(--warning); }
  .tam { margin-left: auto; font-variant-numeric: tabular-nums; color: var(--text-secondary); font-size: 0.85rem; white-space: nowrap; }

  /* Contadores: 2×2 no celular; cada um liga o filtro do mesmo nome. */
  .contadores { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
  .contador { display: flex; flex-direction: column; align-items: flex-start; gap: 2px; text-align: left; padding: 10px 12px;
              border-radius: 12px; border: 1px solid var(--border-subtle); background: var(--surface-raised); font: inherit; color: inherit; }
  .contador.on { border-color: var(--cor); }
  .contador-rotulo { font-size: 0.78rem; color: var(--text-secondary); display: flex; align-items: center; gap: 6px; }
  .contador-rotulo::before { content: ''; width: 8px; height: 8px; border-radius: 50%; background: var(--cor); }
  .contador-n { font-size: 1.4rem; font-weight: 600; font-variant-numeric: tabular-nums; }
  .contador-dica { font-size: 0.75rem; color: var(--text-muted); overflow-wrap: anywhere; }

  .disco { display: flex; flex-direction: column; gap: 8px; padding: 12px; border-radius: 12px; background: var(--surface-raised); }
  .disco p { margin: 0; }
  .barra { display: flex; height: 10px; border-radius: 5px; overflow: hidden; gap: 1px; }
  .barra span { min-width: 2px; }
  .disco-linhas { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; }
  .disco-linha { width: 100%; display: flex; align-items: center; gap: 8px; text-align: left; padding: 6px 4px; min-height: 36px;
                 border: 0; background: transparent; font: inherit; color: inherit; border-radius: 6px; }
  .disco-linha--resto { color: var(--text-muted); }
  .disco-nome { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; min-width: 0; flex: 0 1 auto; }
  .legenda { display: flex; flex-wrap: wrap; gap: 4px 12px; font-size: 0.75rem; color: var(--text-muted); }
  .legenda > span { display: inline-flex; align-items: center; gap: 4px; }

  /* Chips do filtro rolam na horizontal: seis não cabem numa linha de celular. */
  .filtros { display: flex; gap: 6px; overflow-x: auto; margin: 0 -16px; padding: 0 16px; scrollbar-width: none; }
  .filtro { flex: none; display: inline-flex; align-items: center; gap: 6px; min-height: 34px; padding: 0 12px; border-radius: 999px;
            border: 1px solid var(--border-subtle); background: transparent; font: inherit; font-size: 0.85rem; color: inherit; white-space: nowrap; }
  .filtro.on { border-color: var(--border-strong); background: var(--surface-raised); }
  .filtro-n { color: var(--text-muted); font-variant-numeric: tabular-nums; }

  .repo { display: flex; flex-direction: column; gap: 8px; }
  .repo-topo { display: flex; flex-direction: column; gap: 2px; margin-top: 8px; }
  .lote { align-self: flex-start; gap: 8px; padding: 0 16px; border-radius: 8px;
          border: 1px solid color-mix(in srgb, var(--success) 35%, transparent);
          background: color-mix(in srgb, var(--success) 8%, transparent); color: var(--success-text); font-weight: 600; }
  .lote:disabled { opacity: 0.6; }
  .fichas { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 6px; }
  /* A ficha inteira abre o detalhe pelo ::after do título; as sessões ficam por cima e levam à conversa. */
  .ficha { position: relative; display: flex; flex-direction: column; gap: 4px; padding: 10px 12px; border-radius: 10px;
           background: var(--surface-raised); }
  .ficha-topo { display: flex; align-items: baseline; gap: 8px; }
  .abrir { padding: 0; min-height: 0; border: 0; background: transparent; font: inherit; font-weight: 600; color: inherit;
           text-align: left; overflow-wrap: anywhere; }
  .abrir::after { content: ''; position: absolute; inset: 0; border-radius: 10px; }
  .chips, .sessoes, .metricas { display: flex; flex-wrap: wrap; gap: 4px 10px; align-items: center; }
  .chips { gap: 6px; }
  .chip { font-size: 0.72rem; padding: 2px 8px; border-radius: 999px; color: var(--cor);
          background: color-mix(in srgb, var(--cor) 14%, transparent); }
  .sessao { position: relative; z-index: 1; display: inline-flex; align-items: center; gap: 6px; min-height: 32px; padding: 0 10px;
            border-radius: 999px; border: 1px solid var(--border-default); background: var(--surface-inset); font: inherit; font-size: 0.82rem; color: inherit; }
  .sessao-nome { font-weight: 600; }
  .assunto { font-size: 0.85rem; color: var(--text-secondary); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .metricas { font-size: 0.82rem; }
  .subagentes { display: flex; flex-wrap: wrap; align-items: center; gap: 4px 8px; text-align: left; padding: 8px 4px; min-height: 40px;
                border: 0; background: transparent; font: inherit; color: inherit; }
  .sub-titulo { font-weight: 600; font-size: 0.9rem; }
  .seta { display: inline-block; transition: rotate 0.15s; }
  .seta--aberta { rotate: 90deg; }
  .tentar { min-height: 32px; margin-left: 6px; padding: 0 10px; border-radius: 8px; border: 1px solid var(--border-default); font-size: 0.8rem; }
  .ficha .aviso { margin: 0; position: relative; z-index: 1; }
  .legenda-commits { margin: 4px 0 0; font-size: 0.75rem; }

  .sheet { padding: 16px; display: flex; flex-direction: column; gap: 10px; }
  .sheet .libera { margin: 0; font-size: 0.9rem; }
  .title { font-size: 1.05rem; margin: 0; }
  .nome { font-weight: 600; }
  .itens { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 8px; }
  .itens > li { display: flex; flex-direction: column; gap: 2px; }
  .sheet .aviso { margin: 0; }
  .perde { margin: 0; padding-left: 18px; font-family: var(--font-mono); font-size: 0.8rem; overflow-wrap: anywhere; }
  .acoes { display: flex; justify-content: flex-end; gap: 8px; margin-top: 4px; }
  .cancelar { padding: 0 16px; border-radius: 8px; border: 1px solid var(--border-default); }
  .apagar { padding: 0 16px; border-radius: 8px; background: var(--error); color: #fff; font-weight: 600; }
</style>
