// mobile/src/features/config/TranscriptionProviders.tsx
import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { Pressable, Text, TextInput, View } from 'react-native';
import { StyleSheet, useUnistyles } from 'react-native-unistyles';
import {
  editTranscriptionProviderKey, fmtWhen, getTranscriptionProvidersStatus, moveTranscriptionProvider, parseTranscriptionProviders,
  type TranscriptionProviderConfig, type TranscriptionProviderStatus,
} from '@hangar/core';
import { BlockHead, Box, useInputStyle } from './ServerConfigParts';
import { Pill } from './PageHeader';
import { Segmented } from './Segmented';
import { useSettingsColors } from './colors';
import { PROVIDERS, type ServerConfig } from './serverConfig';
import { Icon, type IconName } from '../../ui/Icon';
import * as m from '../../paraglide/messages';

type Status = { state: 'loading' } | { state: 'error'; error: string } | { state: 'ready'; byId: Record<string, TranscriptionProviderStatus> };

/**
 * Serviços de transcrição em ordem (`render_providers` do Rust): o primeiro transcreve, e quem falha ou fica sem cota
 * passa a vez. Servidor cuja leitura não trouxe a lista não mostra o bloco.
 */
export function TranscriptionProviders({ cfg }: { cfg: ServerConfig }) {
  const { theme } = useUnistyles();
  const c = useSettingsColors();
  const input = useInputStyle();
  const [status, setStatus] = useState<Status>({ state: 'loading' });
  const server = cfg.server;
  const present = PROVIDERS in cfg.fields;

  const loadStatus = useCallback(() => {
    if (!server) return () => {};
    let live = true;
    setStatus({ state: 'loading' });
    getTranscriptionProvidersStatus(server)
      .then((r) => { if (live) setStatus({ state: 'ready', byId: Object.fromEntries(r.providers.map((p) => [p.id, p])) }); })
      .catch((e: unknown) => {
        if (live) setStatus({ state: 'error', error: e instanceof Error && e.message ? e.message : m.erro_desconhecido() });
      });
    return () => { live = false; };
  }, [server]);

  // Relê a cada leitura boa da página (abrir e Salvar): a espera muda com a lista.
  useEffect(() => (cfg.load.status === 'ready' && present ? loadStatus() : undefined),
    [cfg.load.status, cfg.fields, present, loadStatus]);

  if (!present) return null;
  const list = parseTranscriptionProviders(cfg.current(PROVIDERS));
  const stored = parseTranscriptionProviders(cfg.fields[PROVIDERS]?.valor);
  const stage = (next: TranscriptionProviderConfig[]) => cfg.stage(PROVIDERS, next);
  const edit = (i: number, item: TranscriptionProviderConfig) => stage(list.map((p, n) => (n === i ? item : p)));
  const kinds = [{ v: 'openai', label: m.native_voice_provider_kind_openai() }, { v: 'elevenlabs', label: m.native_voice_provider_kind_elevenlabs() }] as const;
  const now = Date.now() / 1000;
  const add = () => stage([...list, {
    // ponytail: relógio + sorteio; dois toques nunca colidem na prática.
    id: `p${Date.now().toString(16)}${Math.random().toString(16).slice(2, 6)}`,
    kind: 'openai', name: '', base_url: '', api_key: '', model: '',
  }]);
  const iconButton = (icon: IconName, label: string, onPress: () => void, disabled: boolean) => (
    <Pressable onPress={onPress} disabled={disabled} hitSlop={6} style={[styles.iconBtn, disabled && styles.off]}
      accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ disabled }}>
      <Icon name={icon} size={16} color={c.muted} />
    </Pressable>
  );

  return (
    <>
      <BlockHead title={m.native_voice_providers()} help={m.native_voice_providers_help()}
        right={PROVIDERS in cfg.draft ? <Pill label={m.native_server_undo()} onPress={() => cfg.unstage(PROVIDERS)} /> : null} />
      <Box>
        {list.length === 0 ? (
          <View style={[styles.line, { borderTopColor: c.border }]}>
            <Text style={[styles.help, { color: c.muted }]}>{m.native_voice_providers_empty()}</Text>
          </View>
        ) : null}
        {list.map((p, i) => {
          const state = status.state === 'ready' ? status.byId[p.id] : undefined;
          const name = p.name.trim() || state?.name || (p.kind === 'elevenlabs'
            ? m.native_voice_provider_kind_elevenlabs() : m.native_voice_provider_kind_openai());
          const title = `${i + 1}. ${name}`;
          const until = state?.waiting_until && state.waiting_until > now ? state.waiting_until : null;
          const waiting = until ? m.native_voice_provider_waiting({ until: fmtWhen(until) }) : null;
          const mask = stored.find((s) => s.id === p.id)?.api_key || undefined;
          const keptMask = mask && p.api_key === mask ? mask : null;
          return (
            <View key={p.id} style={[styles.line, styles.item, { borderTopColor: c.border }]}>
              <View style={styles.head}>
                <Text numberOfLines={1} style={[styles.title, { color: c.text }]}>{title}</Text>
                {iconButton('ArrowUp', m.native_voice_provider_up({ name }), () => stage(moveTranscriptionProvider(list, i, -1)), i === 0)}
                {iconButton('ArrowDown', m.native_voice_provider_down({ name }), () => stage(moveTranscriptionProvider(list, i, 1)), i === list.length - 1)}
                <Pressable onPress={() => stage(list.filter((_, n) => n !== i))} hitSlop={6} style={styles.remove}
                  accessibilityRole="button" accessibilityLabel={m.native_voice_provider_remove({ name })}>
                  <Icon name="X" size={14} color={c.muted} />
                  <Text style={[styles.removeText, { color: c.muted }]}>{m.native_server_remove()}</Text>
                </Pressable>
              </View>
              {waiting ? (
                <Text accessibilityLiveRegion="polite" style={[styles.small, { color: theme.tokens.status.warning }]}>
                  {state?.reason ? `${waiting}: ${state.reason}` : waiting}
                </Text>
              ) : null}
              <Segmented options={kinds} value={p.kind} label={title}
                onChange={(v) => edit(i, { ...p, kind: v })} />
              {p.kind === 'openai' ? (
                <Labeled label={m.native_voice_provider_endpoint()}>
                  <TextInput {...input} accessibilityLabel={`${m.native_voice_provider_endpoint()}, ${title}`}
                    placeholder="https://api.groq.com/openai/v1" autoCapitalize="none" autoCorrect={false} keyboardType="url"
                    value={p.base_url} onChangeText={(t) => edit(i, { ...p, base_url: t })} />
                </Labeled>
              ) : null}
              <Labeled label={m.native_voice_provider_key()}>
                {/* Como o ConfigRow: mostra só o digitado; apagar volta à máscara, que mantém a chave guardada. */}
                <TextInput {...input} accessibilityLabel={`${m.native_voice_provider_key()}, ${title}`} secureTextEntry
                  autoCapitalize="none" autoCorrect={false} textContentType="password" autoComplete="off"
                  placeholder={mask ? m.native_server_secret_paste_new() : m.native_server_secret_paste()}
                  value={p.api_key === mask ? '' : p.api_key} onChangeText={(t) => edit(i, editTranscriptionProviderKey(p, t, mask))} />
              </Labeled>
              {keptMask ? (
                <Text style={[styles.small, { color: c.muted }]}>
                  <Text style={{ fontFamily: theme.base.fontMono }}>{keptMask}</Text> · {m.native_server_secret_set()}
                </Text>
              ) : null}
              {p.api_key ? null : (
                <Text accessibilityRole="alert" style={[styles.small, { color: theme.tokens.status.warning }]}>{m.native_voice_provider_missing_key()}</Text>
              )}
              <Labeled label={m.native_voice_provider_model()}>
                {/* Modelo padrão do servidor: identificador, não frase de tela. */}
                <TextInput {...input} accessibilityLabel={`${m.native_voice_provider_model()}, ${title}`}
                  placeholder={p.kind === 'elevenlabs' ? 'scribe_v2' : 'whisper-large-v3'}
                  autoCapitalize="none" autoCorrect={false} value={p.model} onChangeText={(t) => edit(i, { ...p, model: t })} />
              </Labeled>
            </View>
          );
        })}
        <View style={[styles.line, styles.addLine, { borderTopColor: c.border }]}>
          <Pill icon="Plus" label={m.native_voice_provider_add()} onPress={add} />
        </View>
      </Box>
      {status.state === 'error' ? (
        <View style={styles.errorLine}>
          <Text accessibilityRole="alert" style={[styles.help, styles.flex, { color: theme.tokens.status.error }]}>
            {m.native_voice_providers_status_failed({ error: status.error })}
          </Text>
          <Pill label={m.native_server_retry()} onPress={() => { loadStatus(); }} />
        </View>
      ) : null}
    </>
  );
}

function Labeled({ label, children }: { label: string; children: ReactNode }) {
  const c = useSettingsColors();
  return (
    <View style={styles.labeled}>
      <Text style={[styles.small, { color: c.muted }]}>{label}</Text>
      {children}
    </View>
  );
}

const styles = StyleSheet.create({
  line: { borderTopWidth: 1, paddingVertical: 14, paddingHorizontal: 16 },
  item: { gap: 10 },
  addLine: { paddingVertical: 10, flexDirection: 'row' },
  head: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  title: { flex: 1, minWidth: 0, fontSize: 15, fontWeight: '500' },
  iconBtn: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
  off: { opacity: 0.4 },
  remove: { flexDirection: 'row', alignItems: 'center', gap: 4, height: 32, paddingHorizontal: 6 },
  removeText: { fontSize: 13.5, fontWeight: '500' },
  labeled: { gap: 4 },
  small: { fontSize: 13.5, lineHeight: 17 },
  help: { fontSize: 14, lineHeight: 18 },
  errorLine: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 4 },
  flex: { flex: 1 },
});

// frontend/src/components/settings/TranscriptionProviders.svelte
<script lang="ts">
  import type { ConfigServidorStore } from '../../lib/serverConfig.svelte';
  import SegmentedPicker from '../SegmentedPicker.svelte';
  import {
    editTranscriptionProviderKey, getTranscriptionProvidersStatus, moveTranscriptionProvider,
    parseTranscriptionProviders, transcriptionProviderLabel,
    type TranscriptionProviderConfig, type TranscriptionProviderKind, type TranscriptionProviderStatus,
  } from '@hangar/core';
  import { intlLocale } from '../../lib/locale';
  import * as m from '../../paraglide/messages';

  // Ordem da lista = ordem de tentativa. O nome do serviço aparece só no item, nunca no rótulo da
  // capacidade (a seção continua se chamando "Transcrição").
  interface Props { store: ConfigServidorStore }
  let { store }: Props = $props();
  const CHAVE = 'transcription_providers';

  const lista = $derived(parseTranscriptionProviders(store.valorBruto(CHAVE)));
  // Máscara da chave guardada, por id: devolvida intacta, o backend mantém a chave antiga.
  const mascaras = $derived(new Map(parseTranscriptionProviders(store.campos[CHAVE]?.valor).map((p) => [p.id, p.api_key])));

  function gravar(nova: TranscriptionProviderConfig[]) { store.setRascunho(CHAVE, nova); }
  function atualizar(i: number, novo: TranscriptionProviderConfig) {
    gravar(lista.map((p, j) => (j === i ? novo : p)));
  }
  function remover(i: number) { gravar(lista.filter((_, j) => j !== i)); }
  function adicionar() {
    // crypto.randomUUID não existe fora de contexto seguro (PWA por http na rede local).
    const id = Math.random().toString(36).slice(2, 10);
    gravar([...lista, { id, kind: 'openai', name: '', base_url: '', api_key: '', model: '' }]);
  }

  // Espera por cota, lida do servidor editado. Relê quando os campos são trocados (abrir e salvar).
  let status = $state<TranscriptionProviderStatus[] | null>(null);
  let statusErro = $state('');
  let releitura = $state(0);
  $effect(() => {
    void store.campos;
    void releitura;
    if (store.carregando) return;
    let vivo = true;
    statusErro = '';
    getTranscriptionProvidersStatus(store.alvo)
      .then((r) => { if (vivo) status = r.providers; })
      .catch((e) => { if (vivo) statusErro = e instanceof Error ? e.message : String(e); });
    return () => { vivo = false; };
  });
  function emEspera(id: string): TranscriptionProviderStatus | null {
    const s = status?.find((x) => x.id === id);
    return s?.waiting_until && s.waiting_until * 1000 > Date.now() ? s : null;
  }
  const hora = (t: number) => new Date(t * 1000).toLocaleString(intlLocale(), { dateStyle: 'short', timeStyle: 'short' });
  const opcoesTipo = $derived([
    { v: 'openai' as TranscriptionProviderKind, label: m.native_voice_provider_kind_openai(), aria: m.native_voice_provider_kind_openai() },
    { v: 'elevenlabs' as TranscriptionProviderKind, label: m.native_voice_provider_kind_elevenlabs(), aria: m.native_voice_provider_kind_elevenlabs() },
  ]);
</script>

<div class="servicos">
  <p class="ajuda">{m.native_voice_providers_help()}</p>
  {#if statusErro}
    <p class="aviso erro" role="alert">
      {m.native_voice_providers_status_failed({ error: statusErro })}
      <button class="link-btn" onclick={() => releitura++}>{m.config_server_tentar_de_novo()}</button>
    </p>
  {/if}
  {#if lista.length === 0}
    <p class="aviso">{m.native_voice_providers_empty()}</p>
  {:else}
    <ol class="lista">
      {#each lista as p, i (p.id)}
        {@const nome = transcriptionProviderLabel(p)}
        {@const espera = emEspera(p.id)}
        {@const mascara = mascaras.get(p.id)}
        <li class="item">
          <div class="item-cabeca">
            <span class="nome">{nome}</span>
            <div class="acoes">
              <button class="mini" onclick={() => gravar(moveTranscriptionProvider(lista, i, -1))} disabled={i === 0}
                aria-label={m.native_voice_provider_up({ name: nome })} title={m.native_voice_provider_up({ name: nome })}>↑</button>
              <button class="mini" onclick={() => gravar(moveTranscriptionProvider(lista, i, 1))} disabled={i === lista.length - 1}
                aria-label={m.native_voice_provider_down({ name: nome })} title={m.native_voice_provider_down({ name: nome })}>↓</button>
              <button class="mini" onclick={() => remover(i)}
                aria-label={m.native_voice_provider_remove({ name: nome })} title={m.native_voice_provider_remove({ name: nome })}>✕</button>
            </div>
          </div>
          {#if espera}
            <p class="espera" role="status">
              {m.native_voice_provider_waiting({ until: hora(espera.waiting_until!) })}{espera.reason ? `: ${espera.reason}` : ''}
            </p>
          {/if}
          <SegmentedPicker value={p.kind} options={opcoesTipo} ariaLabel={m.voz_servico_tipo()}
            onPick={(v) => atualizar(i, { ...p, kind: v })} />
          <div class="campos">
            {#if p.kind === 'openai'}
              <label class="campo">
                <span class="rot">{m.native_voice_provider_endpoint()}</span>
                <input type="url" autocomplete="off" value={p.base_url} placeholder="https://api.groq.com/openai/v1"
                  oninput={(e) => atualizar(i, { ...p, base_url: e.currentTarget.value })} />
              </label>
            {/if}
            <div class="campo">
              <label class="rot" for={`tp-key-${p.id}`}>{m.native_voice_provider_key()}</label>
              <!-- Igual ao segredo de LinhaConfig: o campo mostra só o que foi digitado; a máscara fica ao lado. -->
              {#if mascara && p.api_key === mascara}
                <span class="mascara">{mascara} <span class="mascara-nota">{m.config_server_configurada()}</span></span>
              {/if}
              <input id={`tp-key-${p.id}`} type="text" autocomplete="off" autocapitalize="off" spellcheck={false}
                value={p.api_key === mascara ? '' : p.api_key}
                placeholder={mascara ? m.config_motores_colar_nova() : m.config_motores_colar()}
                oninput={(e) => atualizar(i, editTranscriptionProviderKey(p, e.currentTarget.value, mascara))} />
              {#if !p.api_key}<span class="falta" role="alert">{m.native_voice_provider_missing_key()}</span>{/if}
            </div>
            <label class="campo">
              <span class="rot">{m.native_voice_provider_model()}</span>
              <input type="text" autocomplete="off" value={p.model} placeholder={p.kind === 'elevenlabs' ? 'scribe_v2' : 'whisper-large-v3'}
                oninput={(e) => atualizar(i, { ...p, model: e.currentTarget.value })} />
            </label>
          </div>
        </li>
      {/each}
    </ol>
  {/if}
  <button class="btn" onclick={adicionar}>{m.native_voice_provider_add()}</button>
</div>

<style>
  /* Container query, nunca media query: quem aperta a linha é a largura do painel. */
  .servicos { container-type: inline-size; display: flex; flex-direction: column; gap: var(--space-2); margin-top: var(--space-2); }
  .lista { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; }
  .item { display: flex; flex-direction: column; gap: var(--space-2); padding: var(--space-3) 0; border-bottom: 1px solid var(--border-subtle); }
  .item-cabeca { display: flex; align-items: center; gap: var(--space-2); }
  .nome { flex: 1 1 auto; min-width: 0; font-size: var(--text-sm); font-weight: 600; color: var(--text-primary); overflow-wrap: anywhere; }
  .acoes { display: flex; gap: 4px; flex-shrink: 0; }
  .mini {
    width: 32px; height: 32px; border-radius: var(--radius-md); background: transparent;
    color: var(--text-secondary); font-size: var(--text-sm);
  }
  .mini:disabled { opacity: 0.35; }
  .espera { margin: 0; font-size: var(--text-xs); color: var(--warning, var(--text-muted)); }
  .campos { display: grid; grid-template-columns: 1fr; gap: var(--space-2); }
  @container (min-width: 520px) { .campos { grid-template-columns: 1fr 1fr; } }
  .campo { display: flex; flex-direction: column; gap: 4px; min-width: 0; }
  .rot { font-size: var(--text-xs); font-weight: 600; color: var(--text-secondary); }
  .campo input {
    height: 36px; padding: 0 10px; min-width: 0;
    border: 1px solid var(--border-subtle); border-radius: var(--radius-md);
    background: var(--surface-inset); color: var(--text-primary);
    font-family: var(--font-ui); font-size: var(--text-sm);
  }
  .mascara { font-family: var(--font-mono); font-size: var(--text-xs); color: var(--text-muted); overflow-wrap: anywhere; }
  .mascara-nota { font-family: var(--font-ui); color: var(--success); }
  .falta { font-size: var(--text-xs); color: var(--warning, var(--error)); }
  .ajuda { margin: 0; font-size: var(--text-xs); color: var(--text-muted); line-height: 1.45; }
  .aviso { font-size: var(--text-sm); color: var(--text-muted); margin: 0; }
  .aviso.erro { color: var(--error); }
  .link-btn { margin-left: var(--space-2); padding: 0; background: none; border: none; color: var(--accent); font-size: inherit; }
  .btn {
    align-self: flex-start; height: 40px; padding: 0 var(--space-4); border-radius: var(--radius-md);
    background: var(--surface-raised); color: var(--text-primary); font-size: var(--text-sm); font-weight: 600;
  }
</style>
