// frontend/src/components/settings/CodexContaLogin.svelte
<script lang="ts">
  import { onMount, untrack } from 'svelte';
  import { serverIdentidade } from '../../lib/auth';
  import { createCodexAccountForServer, prepareCodexAccountForServer,
    getCodexPreparationForServer, startCodexAccountLoginForServer,
    getCodexAccountLoginForServer, cancelCodexAccountLoginForServer, getCodexAccountsForServer,
    codexAccountMessage, contaCodexParaEntrar, type Server, type CodexLoginAttempt, type CodexAccount } from '@hangar/core';
  import { copyText } from '../../lib/clipboard';
  import * as m from '../../paraglide/messages';

  let { server, accountId, oncomplete }: {
    server: Server; accountId?: string; oncomplete: () => void;
  } = $props();
  let name = $state('');
  let account = $state<string | undefined>();
  let attempt = $state<CodexLoginAttempt | null>(null);
  let sync = $state<CodexAccount['sync'] | null>(null);
  let busy = $state(false);
  let error = $state('');
  let generation = 0;
  let controller = new AbortController();
  let timer: ReturnType<typeof setTimeout> | undefined;
  const identity = $derived(serverIdentidade(server));
  const url = $derived.by(() => {
    try {
      const u = new URL(attempt?.verification_url ?? '');
      return u.protocol === 'https:' && !u.username && !u.password ? u.href : null;
    } catch { return null; }
  });
  const failed = (e: unknown) => e instanceof Error ? e.message : m.codex_ui_login_error();

  function show(next: CodexLoginAttempt | null, g: number) {
    if (g !== generation) return;
    attempt = next;
    if (next?.status === 'completed') oncomplete();
  }

  // "Adicionar conta" com a padrao ainda sem login = entrar NELA, sem nome nem conta extra.
  async function entrarNaPadrao(s: Server, g: number, signal: AbortSignal) {
    try {
      const id = contaCodexParaEntrar(await getCodexAccountsForServer(s, signal));
      if (g !== generation || !id) return;
      account = id;
      void read(s, id, g, signal);
    } catch { /* lista indisponivel: segue criando conta nomeada, como antes */ }
  }

  async function read(s: Server, id: string, g: number, signal: AbortSignal) {
    try {
      const next = await getCodexAccountLoginForServer(s, id, signal);
      if (g !== generation) return;
      error = '';
      show(next, g);
      if (next?.status === 'waiting') timer = setTimeout(() => read(s, id, g, signal), 1000);
    } catch (e) {
      if (g === generation) error = failed(e);
    }
  }

  $effect(() => {
    void identity;
    const s = untrack(() => server), id = accountId;
    const g = ++generation;
    controller.abort();
    controller = new AbortController();
    clearTimeout(timer);
    account = id; attempt = null; sync = null; busy = false; error = ''; name = '';
    if (id) void read(s, id, g, controller.signal);
    else void entrarNaPadrao(s, g, controller.signal);
    return () => { ++generation; controller.abort(); clearTimeout(timer); };
  });

  onMount(() => {
    const resume = () => {
      if (document.visibilityState !== 'visible' || !account || busy || attempt?.status !== 'waiting') return;
      const g = ++generation;
      controller.abort();
      controller = new AbortController();
      clearTimeout(timer);
      void read(server, account, g, controller.signal);
    };
    document.addEventListener('visibilitychange', resume);
    return () => document.removeEventListener('visibilitychange', resume);
  });

  async function start() {
    if (busy) return;
    const s = server, g = ++generation;
    const signal = controller.signal;
    clearTimeout(timer);
    busy = true; error = '';
    try {
      let id = account;
      if (!id) {
        const created = await createCodexAccountForServer(s, name.trim());
        if (g !== generation) return;
        account = id = created.id;
      }
      const prepared = await prepareCodexAccountForServer(s, id);
      if (g !== generation) return;
      sync = prepared;
      while (sync.status === 'running') {
        await new Promise<void>((resolve) => {
          const t = setTimeout(resolve, 1000);
          signal.addEventListener('abort', () => { clearTimeout(t); resolve(); }, { once: true });
        });
        if (g !== generation) return;
        const next = await getCodexPreparationForServer(s, id, signal);
        if (g !== generation) return;
        sync = next;
      }
      if (sync.status !== 'ready') return;
      const next = await startCodexAccountLoginForServer(s, id);
      if (g !== generation) return;
      show(next, g);
      if (next.status === 'waiting') timer = setTimeout(() => read(s, id, g, signal), 1000);
    } catch (e) {
      if (g === generation) error = failed(e);
    } finally { if (g === generation) busy = false; }
  }

  async function cancel() {
    if (!account || !attempt || busy) return;
    const s = server, id = account, attemptId = attempt.attempt_id, g = ++generation;
    clearTimeout(timer); busy = true; error = '';
    try { show(await cancelCodexAccountLoginForServer(s, id, attemptId), g); }
    catch (e) { if (g === generation) error = failed(e); }
    finally { if (g === generation) busy = false; }
  }
</script>

<div class="codex-login" aria-busy={busy}>
  <p>{m.codex_ui_oauth()}</p>
  {#if !account}
    <label>{m.novacred_nome_conta()}<input bind:value={name} disabled={busy} /></label>
  {/if}
  {#if sync?.status === 'running'}<p role="status">{m.codex_ui_preparing()}</p>
  {:else if sync?.status === 'ready'}<p role="status">{m.codex_ui_inherited()}</p>{/if}
  {#if sync?.trust_pending}<p role="status">{m.harness_codex_confianca()}</p>{/if}
  {#each sync?.issues ?? [] as issue, i (i)}<p role="alert">{codexAccountMessage(issue)}</p>{/each}
  {#if sync && sync.status !== 'running' && sync.status !== 'ready' && !sync.issues.length}
    <p role="alert">{m.codex_ui_prepare_error()}</p>
  {/if}
  {#if attempt?.status === 'waiting'}
    <p role="status">{m.novacred_codex_aguardando()}</p>
    {#if url}<a href={url} target="_blank" rel="noopener noreferrer">{url}</a>{/if}
    {#if attempt.user_code}
      <code>{attempt.user_code}</code>
      <button type="button" onclick={() => copyText(attempt!.user_code!).catch((e) => error = failed(e))}>{m.comum_copiar_codigo()}</button>
    {/if}
    <button type="button" disabled={busy} onclick={cancel}>{m.codex_ui_cancel_login()}</button>
    {#if error}<button type="button" onclick={() => account && read(server, account, generation, controller.signal)}>{m.novacred_codex_tentar()}</button>{/if}
  {:else if attempt?.status === 'completed'}
    <p role="status">{m.novacred_codex_concluido()}</p>
  {:else}
    {#if attempt?.error}<p role="alert">{codexAccountMessage(attempt.error)}</p>{/if}
    {#if attempt?.status === 'cancelled'}<p role="status">{m.codex_ui_cancelled()}</p>{/if}
    <button type="button" disabled={busy || (!account && !name.trim())} onclick={start}>
      {busy ? m.codex_ui_preparing() : m.contas_entrar()}
    </button>
  {/if}
  {#if error}<p role="alert">{error}</p>{/if}
</div>

<style>
  .codex-login { display: flex; flex-direction: column; gap: var(--space-3); min-width: 0; }
  p { margin: 0; font-size: var(--text-sm); }
  label { display: flex; flex-direction: column; gap: var(--space-2); }
  input { background: var(--surface-inset); color: var(--text-primary); border: 1px solid var(--border-default); border-radius: var(--radius-sm); padding: var(--space-3); }
  button { background: var(--surface-raised); color: var(--text-primary); border: 1px solid var(--border-default); border-radius: var(--radius-sm); min-height: 44px; padding: var(--space-2); cursor: pointer; }
  button:disabled { opacity: .55; cursor: default; }
  a, code { overflow-wrap: anywhere; color: var(--accent); }
  [role='alert'] { color: var(--error); }
  button:focus-visible, input:focus-visible, a:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
</style>

// mobile/src/features/config/CodexContaLogin.tsx
import { useEffect, useRef, useState } from 'react';
import { AppState, Pressable, Text, TextInput, View } from 'react-native';
import { StyleSheet } from 'react-native-unistyles';
import * as Linking from 'expo-linking';
import * as Clipboard from 'expo-clipboard';
import { createCodexAccountForServer, prepareCodexAccountForServer, getCodexPreparationForServer,
  startCodexAccountLoginForServer, getCodexAccountLoginForServer, cancelCodexAccountLoginForServer,
  getCodexAccountsForServer, codexAccountMessage, contaCodexParaEntrar,
  type Server, type CodexAccount, type CodexLoginAttempt } from '@hangar/core';
import * as m from '../../paraglide/messages';

export function CodexContaLogin({ server, accountId, onComplete }: {
  server: Server; accountId?: string; onComplete: () => void;
}) {
  const [name, setName] = useState('');
  const [account, setAccount] = useState(accountId);
  const [attempt, setAttempt] = useState<CodexLoginAttempt | null>(null);
  const [sync, setSync] = useState<CodexAccount['sync'] | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const generation = useRef(0);
  const controller = useRef(new AbortController());
  const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const complete = useRef(onComplete);
  complete.current = onComplete;
  const fail = (e: unknown) => e instanceof Error ? e.message : m.codex_ui_login_error();
  const stop = () => { clearTimeout(timer.current); controller.current.abort(); controller.current = new AbortController(); return ++generation.current; };

  function show(next: CodexLoginAttempt | null) {
    setAttempt(next);
    if (next?.status === 'completed') complete.current();
  }
  async function read(s: Server, id: string, g: number, signal: AbortSignal) {
    clearTimeout(timer.current);
    try {
      const next = await getCodexAccountLoginForServer(s, id, signal);
      if (g !== generation.current) return;
      setError(''); show(next);
      if (next?.status === 'waiting') timer.current = setTimeout(() => void read(s, id, g, signal), 1000);
    } catch (e) { if (g === generation.current) setError(fail(e)); }
  }
  // "Adicionar conta" com a padrao ainda sem login = entrar NELA, sem nome nem conta extra.
  async function entrarNaPadrao(s: Server, g: number, signal: AbortSignal) {
    try {
      const id = contaCodexParaEntrar(await getCodexAccountsForServer(s, signal));
      if (g !== generation.current || !id) return;
      setAccount(id);
      void read(s, id, g, signal);
    } catch { /* lista indisponivel: segue criando conta nomeada, como antes */ }
  }
  useEffect(() => {
    const g = stop(), signal = controller.current.signal;
    setAccount(accountId); setAttempt(null); setSync(null); setBusy(false); setError(''); setName('');
    if (accountId) void read(server, accountId, g, signal);
    else void entrarNaPadrao(server, g, signal);
    return () => { stop(); };
  }, [server.id, server.baseUrl, server.token, accountId]);
  useEffect(() => {
    const listener = AppState.addEventListener('change', state => {
      if (state === 'active' && account && !busy && attempt?.status === 'waiting') {
        const g = stop();
        void read(server, account, g, controller.current.signal);
      }
    });
    return () => listener.remove();
  }, [server, account, busy, attempt?.status]);

  async function start() {
    if (busy) return;
    const s = server, g = stop(), signal = controller.current.signal;
    setBusy(true); setError('');
    try {
      let id = account;
      if (!id) {
        const created = await createCodexAccountForServer(s, name.trim());
        if (g !== generation.current) return;
        id = created.id; setAccount(id);
      }
      let prepared = await prepareCodexAccountForServer(s, id);
      if (g !== generation.current) return;
      setSync(prepared);
      while (prepared.status === 'running') {
        await new Promise<void>(resolve => {
          const done = () => { clearTimeout(t); signal.removeEventListener('abort', done); resolve(); };
          const t = setTimeout(done, 1000); signal.addEventListener('abort', done, { once: true });
        });
        if (g !== generation.current) return;
        prepared = await getCodexPreparationForServer(s, id, signal);
        if (g !== generation.current) return;
        setSync(prepared);
      }
      if (prepared.status !== 'ready') return;
      const next = await startCodexAccountLoginForServer(s, id);
      if (g !== generation.current) return;
      show(next);
      if (next.status === 'waiting') timer.current = setTimeout(() => void read(s, id, g, signal), 1000);
    } catch (e) { if (g === generation.current) setError(fail(e)); }
    finally { if (g === generation.current) setBusy(false); }
  }
  async function cancel() {
    if (!account || !attempt || busy) return;
    const s = server, id = account, attemptId = attempt.attempt_id, g = stop();
    setBusy(true); setError('');
    try {
      const next = await cancelCodexAccountLoginForServer(s, id, attemptId);
      if (g === generation.current) show(next);
    } catch (e) { if (g === generation.current) setError(fail(e)); }
    finally { if (g === generation.current) setBusy(false); }
  }
  async function external(copy: boolean) {
    const g = generation.current;
    try {
      if (copy && attempt?.user_code) await Clipboard.setStringAsync(attempt.user_code);
      else {
        const url = new URL(attempt?.verification_url ?? '');
        if (url.protocol !== 'https:' || !url.hostname || url.username || url.password) throw new Error(m.codex_ui_login_error());
        await Linking.openURL(url.href);
      }
    } catch (e) { if (g === generation.current) setError(fail(e)); }
  }
  const button = (label: string, action: () => void, disabled = busy) => (
    <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={action} style={styles.button}><Text style={styles.text}>{label}</Text></Pressable>
  );
  return <View style={styles.root}>
    <Text style={styles.text}>{m.codex_ui_oauth()}</Text>
    {!account ? <TextInput accessibilityLabel={m.novacred_nome_conta()} placeholder={m.novacred_nome_conta()} value={name} onChangeText={setName} editable={!busy} autoCapitalize="none" style={styles.input} /> : null}
    {sync ? <Text style={styles.text}>{sync.status === 'running' ? m.codex_ui_preparing() : sync.status === 'ready' ? m.codex_ui_inherited() : m.codex_ui_prepare_error()}</Text> : null}
    {sync?.trust_pending ? <Text style={styles.text}>{m.harness_codex_confianca()}</Text> : null}
    {sync?.issues.map((issue, i) => <Text accessibilityRole="alert" style={styles.error} key={i}>{codexAccountMessage(issue)}</Text>)}
    {attempt?.status === 'waiting' ? <>
      <Text style={styles.text}>{m.novacred_codex_aguardando()}</Text>
      {attempt.user_code ? <><Text selectable style={styles.text}>{attempt.user_code}</Text>{button(m.comum_copiar_codigo(), () => void external(true))}</> : null}
      {attempt.verification_url ? button(m.term_abrir_link(), () => void external(false)) : null}
      {button(m.codex_ui_cancel_login(), () => void cancel())}
      {error ? button(m.novacred_codex_tentar(), () => { if (account) { const g = stop(); void read(server, account, g, controller.current.signal); } }) : null}
    </> : attempt?.status === 'completed' ? <Text style={styles.text}>{m.novacred_codex_concluido()}</Text> : <>
      {attempt?.error ? <Text accessibilityRole="alert" style={styles.error}>{codexAccountMessage(attempt.error)}</Text> : null}
      {attempt?.status === 'cancelled' ? <Text style={styles.text}>{m.codex_ui_cancelled()}</Text> : null}
      {button(busy ? m.codex_ui_preparing() : m.contas_entrar(), () => void start(), busy || (!account && !name.trim()))}
    </>}
    {error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}
  </View>;
}
const styles = StyleSheet.create(theme => ({
  root: { gap: theme.base.space[2] },
  text: { color: theme.tokens.text.primary },
  error: { color: theme.tokens.status.error },
  button: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 12, borderWidth: 1, borderColor: theme.tokens.border.default, borderRadius: theme.base.radius.md },
  input: { minHeight: 44, color: theme.tokens.text.primary, borderWidth: 1, borderColor: theme.tokens.border.default, borderRadius: theme.base.radius.md, paddingHorizontal: 12 },
}));
